services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  redoc:
    build:
      context: ./redoc
      target: runtime
    command: "node_modules/.bin/webpack serve --mode=development --env playground --hot --config pim/webpack.config.ts"
    working_dir: /srv/app
    user: "${DOCKER_UID:-1000}"
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=developer.akeneo.local
    volumes:
      - "./redoc:/srv/app:rw"
      - "${YARN_CACHE_FOLDER:-~/.cache/yarn}:/home/node/.cache/yarn"
